# Cross-Compile Reference Deployment

name: Cross-compile reference deployment

on:
  push:
    branches: [ devel, release/** ]
  pull_request:
    branches: [ devel, release/** ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/actions/spelling/**'
      - '.github/ISSUE_TEMPLATE/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'devel') && !contains(github.ref, 'release/')}}

jobs:

  setup-cross-compile:
    uses: kevin-f-ortega/fprime/.github/workflows/reusable-setup-aarch64-linux.yml@sock-testing

  cross-compile:
    runs-on: ubuntu-latest
    needs: setup-cross-compile
    steps:
      # Build the reference deployment
      - name: "Build Reference Deployment"
        run: |
          cat /tmp/a/a.txt
