# Cross-Compile Reference Deployment

name: Cross-compile reference deployment

on:
  push:
    branches: [ devel, release/** ]
  pull_request:
    branches: [ devel, release/** ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/actions/spelling/**'
      - '.github/ISSUE_TEMPLATE/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'devel') && !contains(github.ref, 'release/')}}

jobs:

  cross-compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup cross-compiler
        uses: kevin-f-ortega/fprime-actions/setup-aarch64-toolchain@aarch64-linux-cross-compile

      - name: Verify compiler is in PATH
        run: |
          which aarch64-none-linux-gnu-gcc
          aarch64-none-linux-gnu-gcc -v