# Cross-Compile Reference Deployment

name: Cross-compile reference deployment

on:
  push:
    branches: [ devel, release/** ]
  pull_request:
    branches: [ devel, release/** ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/actions/spelling/**'
      - '.github/ISSUE_TEMPLATE/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'devel') && !contains(github.ref, 'release/')}}

jobs:

  cross-compile:
    uses: kevin-f-ortega/fprime/.github/workflows/reusable-setup-aarch64-linux.yml@sock-testing
    with:
      runs_on: ubuntu-latest

  run-test:
    needs: cross-compile
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout F´ Repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: "Download Build Artifacts"
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - name: "List files from cross-compile job"
        run: |
          ls -la build-artifacts